### ISSUE TITLE
Dudas para crear github pages del repositorio

### ISSUE THREAD

**Issue by Raul-Alv** [Arquisoft/faq#10]
Hola, para poder hacer que nuestro repositorio haga uso de github pages, ¿Cómo deberíamos activarlo, ya que desde el repositorio en Arquisoft no podemos acceder a los ajustes de este? ¿Se ha de hacer un fork y crearlo en él o hay alguna otra forma?

**Comment by labra** [comment]
En realidad no es necesario que tengáis github pages de los repositorios porque la documentación se desplegaba automáticamente en la carpeta docs de cada proyecto. 

No obstante, ya que lo dices y por si queréis incluir alguna otra información sobre el proyecto que siempre queda más chula que el README de github, acabo de activar las github pages en todos vuestros repositorios. 

Los he creado con una de las plantillas de github y no contienen apenas contenido. El contenido se despliega a partir del raíz de la rama "gh_pages". 

A modo de ejemplo, en radarin_0, la página web que se desplega es: https://arquisoft.github.io/radarin_0/

Y el código fuente está en la [rama gh_pages](https://github.com/Arquisoft/radarin_0/tree/gh-pages)

Podéis ver que ahora ya los tenéis activados también en vuestros repositorios si los queréis utilizar.

Por cierto, al ir activándolos, he visto que en muchos grupos estaba fallando la integración continua, quizá por éso no os está visualizando tampoco la documentación (solo se despliega si pasan los tests). Es algo que sí tenéis que corregir.
