### ISSUE TITLE
Error en el despliegue a Heroku

### ISSUE THREAD

**Issue by rmonvfer** [Arquisoft/faq#11]
Al hacer un despliegue desde Github Actions obtenemos el siguiente error:

![image](https://user-images.githubusercontent.com/42870707/113855220-15215680-97a0-11eb-976d-7701652c6b72.png)

Por la información que hemos encontrado, parece que durante la preparación del proyecto para el despliegue se realizan algunos cambios en el repositorio, por lo que tendríamos que realizar un commit para actualizarlo.

Ver [esta issue](https://github.com/AkhileshNS/heroku-deploy/issues/26)

**Comment by DJStatikVX** [comment]
Tenemos el mismo problema en el equipo ES1B. He estado unos días investigando y no he dado con ninguna posible solución adaptada a nuestro dominio. Espero que los profesores puedan echarnos una mano.

**Comment by pglez82** [comment]
Da la impresión que alguien ha hecho un push directamente al remote heroku saltándose github actions y entonces ahora da ese fallo.

Probad a meter `dontuseforce: true` en el job `deploy-webapp` dentro del action `heroku-deploy` a ver si así se arregla.

Esto ya pasó con otro grupo al principio del curso y creo que cuando metí eso se arregló:

https://github.com/Arquisoft/radarin_es3a/commit/f40a3d20d3a8616b5dd8acfd97a3628df7da1397#diff-075b4094db52e0265079eb74df1e3a62c93ac2d5e1f374d8b578abaf540c3952

Cuando lo probéis comentar por aquí si ha funcionado o no.

**Comment by DJStatikVX** [comment]
Gracias por aportar esta posible solución. Desafortunadamente sigue fallando: https://github.com/Arquisoft/radarin_es1b/runs/2294725189

**Comment by pglez82** [comment]
Si, el error despista un poco la verdad. El problema no tiene nada que ver con Heroku. En vuestro caso concreto (y en el de @rmon-vfer también), la linea clave está en:
`The command '/bin/sh -c npm run build' returned a non-zero code: 1`
Esto lo que quiere decir es que el action de desplegar a Heroku está creando la imagen de docker de la webapp para desplegarla y este proceso está fallando. He clonado vuestro proyecto en local y he construido la imagen de docker del webapp localmente y también falla. El error concretamente es:

```
Creating an optimized production build...
Failed to compile.

./src/components/friends/FriendsTabs.jsx
Cannot find module: 'react-swipeable-views'. Make sure this package is installed.

You can install this package by running: npm install react-swipeable-views.
```
Falla al crear la versión de produción de la página porque hay una librería que estáis usando que parece que no tenéis en el package.json.

Resumiendo, probad que las imágenes de docker funcionan en local ya que github actions las va a usar para desplegar en Heroku vuestra aplicación.

**Comment by DJStatikVX** [comment]
Mil gracias, parece que esto ha funcionado. Tienes razón en que este tipo de fallos viene bien detectarlos intentando desplegarlos en local.
