### ISSUE TITLE
Error permisos RestApi

### ISSUE THREAD

**Issue by PascualDaniel** [Arquisoft/faq#12]
Con solid-node-client haciendo el login en restapi  en https://inrupt.net/ , me sale este error: 
![image](https://user-images.githubusercontent.com/71436553/114302777-e15d6e00-9aca-11eb-86b6-1bd5b9c223ba.png)

Y juraría que tengo todos los permisos:
![image](https://user-images.githubusercontent.com/71436553/114302798-03ef8700-9acb-11eb-90d2-4bbe4835a397.png)
No se si falta alguno o es otro tipo de error.

**Comment by UO270571** [comment]
Hola, no se si ya habéis solucionado el problema, pero si estáis pasando https://inrupt.net/ como proveedor igual se soluciona quitando la última barra, es decir, escribiendo https://inrupt.net.
En nuestro grupo tenemos todos los pods en solidcommunity.net y si escribo https://solidcommunity.net/ en lugar de https://solidcommunity.net también me da un error 403.

**Comment by PascualDaniel** [comment]
Todavía no, ese error lo solucionamos ya pero surgio otro que hace que la session no inicie sesion. Sale esto si le hago le hago un log:
`undefined
{
  isLoggedIn: false,
  info: { isLoggedIn: false },
  fetch: [Function: bound ],
  logout: [Function: logout]
}`
el undefined es el webID

**Comment by UO270571** [comment]
Por lo que he leído en la documentación de solid-node-client parece que el inicio de sesión con usuario y contraseña solo vale con pods de solidcommunity.net. Para iniciar sesión en un pod de inrupt habría que seguir [este proceso](https://github.com/solid/solid-node-client#authentication-for-ess-style-pods). 

Sin embargo, todo ese proceso me parece excesivo para un usuario normal, por lo que yo os recomendaría usar pods de solidcommunity.net en lugar de los de inrupt.

**Comment by PascualDaniel** [comment]
Lo probé como tu dijiste y me sigue sin funcionar, me da el mismo error. Voy a intentarlo de la otra manera,

**Comment by UO270571** [comment]
He estado mirando más el problema y **sí** se puede hace login en pods de inrupt.net usando usuario y contraseña. Con los que no se puede hacer login son los de Inrupt Pod Spaces.

Por lo tanto no sé por qué no se inicia sesión cuándo hacéis login, ya que si se produjese algún problema al iniciar sesión la función `login` debería lanzar un error en lugar de dejar la sesión sin iniciar.
