### ISSUE TITLE
Fallo al desplegar heroku con el login

### ISSUE THREAD

**Issue by cova-vega** [Arquisoft/faq#18]
Nos da este fallo al desplegar heroku como que no encuentra el login en el actions de git
![image](https://user-images.githubusercontent.com/56292685/116517397-2eb14c00-a8cf-11eb-9667-30f4fafedf6a.png)

Siguiendo estas instrucciones para actualizar el repositorio en heroku y acceder a heroku
![image](https://user-images.githubusercontent.com/56292685/116517266-01fd3480-a8cf-11eb-9688-bcc2b62fe751.png)

He accedido tanto por heroku CLI como desde la aplicación conectandolo con nuestro repostorio y nos sale este error
![image](https://user-images.githubusercontent.com/56292685/116517550-6cae7000-a8cf-11eb-9bbd-8f939e02c99c.png)

![image](https://user-images.githubusercontent.com/56292685/116517597-7d5ee600-a8cf-11eb-8955-6913dccf8ac2.png)

**Comment by cidinene** [comment]
Hola,
Viendo los mensajes de github actions , veo  que github  no consigue loguearse.
Hace 2 meses funcionaba, y no veo cambios en la configuración del despliegue..he intentado conectarme a heroku pero el login/password no me va...¿Habéis cambiado la clave?yo creo que git no está enviando nada porque no logra conectarse..
Si vosotros podéis acceder a heroku , en la parte de settings tenéis la api key que debéis configurar en github -> settings -> secrets
Os paso el enlace donde está indicado dónde recuperar esa key

https://help.heroku.com/PBGP6IDE/how-should-i-generate-an-api-key-that-allows-me-to-use-the-heroku-platform-api

**Comment by cova-vega** [comment]
Se solucionó el problema ese ya ahora nos sale este que te indicamos en esta issue en nuestro repositorio https://github.com/Arquisoft/radarin_es6a/issues/36
