### ISSUE TITLE
Problema desplegando la App en Heroku

### ISSUE THREAD

**Issue by GermanDiazGlez** [Arquisoft/faq#21]
En local el comando heroku container:login nos funciona correctamente, pero cuando intentamos subirlo a GitHub nos sale el siguiente error:
(En local)
![image](https://user-images.githubusercontent.com/56638034/116779597-930f0f80-aa77-11eb-94ef-3daabb4aa2f5.png)
(En github)
![image](https://user-images.githubusercontent.com/56638034/116779601-9904f080-aa77-11eb-8db8-bae65b55ce37.png)
He cogido la Heroku_ApiKey y se la he vuelto a meter a GitHub y nada.
Además si intento desplegar la app a mano en heroku me dice lo siguiente:
![image](https://user-images.githubusercontent.com/56638034/116779664-ea14e480-aa77-11eb-938e-cbd2a41237cf.png)

¿Alguien que me ayude por favor?

**Comment by GermanDiazGlez** [comment]
Encontré una forma de regenerar la API_KEY desde Heroku, se la volví a pasar a GitHub y....
![image](https://user-images.githubusercontent.com/56638034/116780087-8cce6280-aa7a-11eb-8785-02b209ce9f3f.png)
Funcionó!

**Comment by GermanDiazGlez** [comment]
Problema con el despliegue de la RestApi:
![image](https://user-images.githubusercontent.com/56638034/116780588-f7cd6880-aa7d-11eb-84c4-d2ec668f03f0.png)
Como nuestro equipo debe de ser el único que utiliza firebase, no nos vale la configuración por defecto que nos dieron los profesores, por tanto no se muy bien que poner aquí: 
![image](https://user-images.githubusercontent.com/56638034/116781029-9e1a6d80-aa80-11eb-836a-db19760d33ad.png)
Obtuve de firebase una API_KEY y se la pasé a los secrets de GitHub pero no me parece que esté bien...

**Comment by GermanDiazGlez** [comment]
@cidinene

**Comment by UO270571** [comment]
Hola, creo que el problema tiene que ver con la línea 20 de vuestro Dockerfile de la restapi. Estáis haciendo un ADD de la carpeta ./models, pero esa carpeta no está en vuestro repositorio. Supongo que eliminando esa línea desaparecerá el problema. Espero que os sea de ayuda

**Comment by GermanDiazGlez** [comment]
MUCHISIMAS GRACIAS David!! Era eso, un millon de gracias por dedicar tu tiempo a echarme una mano. :)
![image](https://user-images.githubusercontent.com/56638034/116796065-fc276f00-aad9-11eb-9b86-65d42164afe0.png)
