### ISSUE TITLE
Fallo test webapp

### ISSUE THREAD

**Issue by alvarodelafuentefdez** [Arquisoft/faq#22]
Hola buenas, nos está dando un fallo que no logramos resolver durante la ejecución de las pruebas:

![image](https://user-images.githubusercontent.com/71430148/116789168-d84e3400-aaad-11eb-954d-26106574fecb.png)

El código de la prueba es el siguiente:

![image](https://user-images.githubusercontent.com/71430148/116789235-295e2800-aaae-11eb-99ed-63de75712ff1.png)

Muchas gracias.

**Comment by vitusuarez** [comment]
El error hace referencia a esta clase.
![image](https://user-images.githubusercontent.com/78354682/116810711-9ec90780-ab45-11eb-95a2-c5eb6fb757ac.png)
