### ISSUE TITLE
Format of seminar report

### ISSUE THREAD

**Issue by labra** [Arquisoft/faq#27]
I have received this question:

> Hello, teacher, I had a doubt regarding the document that we have to deliver with the seminar presentation, I am not sure about what we have to put exactly in it. Do we have to make a kind of summary of every point of the presentation?

And my answer was: It is a report about the topic that you have to do the presentation from your point of view...the format is free and the idea is that you should try to talk about that topic from your point of view. You can think of it like a short blog post about that topic. Of course, you can refer to the things that you are planning to say in the presentation.

**Comment by UO277653** [comment]
Is it okay if the document has 3 pages instead of 2? Because we have tried reducing it but we found it a bit difficult to reach 2.

**Comment by labra** [comment]
Yes, it is OK, the recommended size is 2 pages but given that it is inspired by a blog post, and the posts are usually read on the web without a given page size, the page number is approximate.
