### ISSUE TITLE
Regarding the self report for the first deliverable

### ISSUE THREAD

**Issue by UO277653** [Arquisoft/faq#28]
Hello, I have some doubts about the self report that we have to do for next week, I understand that each member has to create an issue where the tasks done are described, but I am confused about the "report of the team", what does it mean exactly? Thanks in advance 🙂

**Comment by labra** [comment]
Ops...I have re-read the message and there was a typo there. It should say "the repo of the team", I mean, in each team's repository.

**Comment by labra** [comment]
I'm closing the issue for cleanup
