### ISSUE TITLE
Standard SOLID

### ISSUE THREAD

**Issue by SergioArroni** [Arquisoft/faq#29]
Hello, message to all PL groups, can we all coordinate to use the same standard in SOLID?

**Comment by AnaOstio** [comment]
el grupo 2es_c está de acuerdo en realizar un mismo estandar

**Comment by NuriaIF** [comment]
The group es3c propose that we can add:
{
'personal_identification' : 'dni/passport',
'name' : 'Sergio Arroni del Riego',
'password' : '*****',
'location' : [
{
'Country: Spain,
Province: Asturias,
City: Gijón,
Street: X,
Nº: X,
Floor: X'
}
]
}

**Comment by hectmg** [comment]
Buenas, nuestro grupo esta de acuerdo en todos estos campos que proponeís pero, ¿No faltaría añadir uno más relativo al número de teléfono de contacto ?  (Para, por ejemplo,  facilitarselo al repartidor si la persona que hace la compra no se encuentra en la dirección indicada. 😄 

También nosotros creemos que sería más optimo añadir zip code y separar el apellido.

Os dejamos aquí nuestra propuesta:
```
{
'personal_identification' : 'dni/passport',
'name' : 'Name',
'surname': 'Surname'
'password' : '*****',
'phone': 1234567
'location' : [
{
'country': 'Spain',
'province': 'Asturias',
'city': 'Gijón',
'zip_code': '3312',
'street': 'X',
'number': 'X',
'floor': X'
'floor_number': '7'
}
]
}
```

**Comment by SergioArroni** [comment]
Perfect! We could also add the email and it would look like this: 😃 
{
'personal_identification' : 'dni/passport',
'name' : 'Name',
'surname': 'Surname', 
'password' : '*****',
'email' : 'JA@uniovi.es',
'phone': 123456756,
'location' : [
{
'country': 'Spain',
'province': 'Asturias',
'city': 'Gijón',
'zip_code': '3312',
'street': 'X',
'number': 'X',
'floor': 'X',
'floor_number': '7'
}
]
}

**Comment by PascualDaniel** [comment]
Una cosa, creo que ya existe un estándar para la dirección y diferentes cosas del perfil. En la imagen se puede ver como añadirlo:

![image](https://user-images.githubusercontent.com/71436553/157007215-4081cfbb-a22a-4551-a782-03cd580c61a7.png)
Aparte su formato es este: 

![image](https://user-images.githubusercontent.com/71436553/157007404-69c27ffd-c78d-4fda-9575-a25bcc9ca0bc.png)

Aunque si queréis seguir con el formato Json vuestro yo me cambiaria.

**Comment by labra** [comment]
Sí, en mi opinión, es buena idea no re-inventar la rueda y apoyarse en cosas que ya existan. 

Si ya hay vocabularios para declarar direcciones, de cara la interoperabilidad no solamente con vuestras aplicaciones de la asignatura sino con cualquier otra aplicación del ecosistema SOLID, puede ser buena idea apoyarse en dichos vocabularios, o hacer una propuesta de un vocabulario que sea compatible con los ya existentes. 

A lo mejor es buena idea que hagáis una recopilación de vocabularios existentes que permitan definir direcciones para ver qué propiedades usáis de unos u otros.

Hace 2 cursos la práctica consistía en el uso de rutas y también surgió la misma problemática de la interoperabilidad, en dicho curso, creamos un repositorio común en el que se hizo un pequeño estándar sobre rutas...podéis ver el repositorio que se hizo aquí: https://arquisoft.github.io/viadeSpec/ y la discusión que se hizo a través de issues aquí: https://github.com/Arquisoft/viadeSpec/issues

Si queréis, podemos crear otro repositorio llamado `dedeSpec` para que podáis trabajar en esa especificación común.
