### ISSUE TITLE
Problem with CORS

### ISSUE THREAD

**Issue by gsusag00** [Arquisoft/faq#30]
I was writing some of the Restapi functionality (getting a product in this case) and it keeps failing because of CORS, this were the messages that it gave me.

 Solicitud de origen cruzado bloqueada: La misma política de origen no permite la lectura de recursos remotos en http://localhost:5000/api/products/Sudadera%20Nike. (Razón: Solicitud CORS sin éxito). Código de estado: (null).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.

Did i forget to take into account some configuration files?

Here is the code of the api calls.

### In restapi/api.ts

```
api.get("/products/:id",async (req: Request, res:Response): Promise<Response> => {
    var  id = req.params.id;
    console.log(id);
    const product = Product.findOne({name:id});
    if(!product) {
      return res.status(404).json({message: 'Product with name "${name}" not found'});
    }
    return res.status(200).send(product);
});
```

### In /webapp/src/api/api.ts

```
export async function getProduct(id:string):Promise<IProduct> {
  const apiEndPoint = process.env.REACT_APP_API_URI|| 'http://localhost:5000/api'
  var str:string = '/products/'+id;
  let response = await fetch(apiEndPoint+str);
  console.log("We got" + response.json());
  return response.json();
}
```

**Comment by gsusag00** [comment]
Nevermind I already found the error, it was that I wasnt using the keyword await on the /restapi/api.ts call

**Comment by labra** [comment]
Great that you found the error. 

I'll close the issue for cleanup.
