### ISSUE TITLE
Ayuda generated-vocab-commons

### ISSUE THREAD

**Issue by PascualDaniel** [Arquisoft/faq#31]
Estoy intentando sacar la dirección del Pod, pero al tener un formato con una dirección aparte, no se como moverse por los nodos.
Probé esto y bastantes posibilidades entre medias:
` 
  <Text property={VCARD.hasAddress.iri.value} />
  <Text property={VCARD.hasAddress.value} />
 <Text property={VCARD.street_address.rdfFactory.namedNode(VCARD.hasAddress.value).value} />
`
Usando estas librerías:

> import { useSession, CombinedDataProvider, Image, LogoutButton, Text } from "@inrupt/solid-ui-react";
> import { Button, Card, CardActionArea, CardContent, Container, Typography } from "@material-ui/core";
> import { FOAF,RDF, VCARD } from "@inrupt/lit-generated-vocab-common";

Y da este error:
`Error: No value found for property.`

Por  lo que he visto  [aqui](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/use-vocabularies/) quiza se puede hacer de otra manera.

**Comment by pglez82** [comment]
Quizás esta respuesta que di a otra issue te pueda servir de ayuda.

https://github.com/Arquisoft/dede_en2b/issues/54#issuecomment-1066491032

Saludos,

Pablo

**Comment by labra** [comment]
I close this issue as it seems it hsa already been answered.
