### ISSUE TITLE
Estandarización API

### ISSUE THREAD

**Issue by labra** [Arquisoft/faq#35]
En el foro de dudas del campus virtual en españól, un estudiante ha preguntado lo siguiente:

> Abro este hilo para decidir como va a funcionar la interoperabilidad entre las diferentes aplicaciones de la asignatura. Hay que decidir que devuelve cada petición de la API y el formato en el que se devuelve.

Como creo que puede ser una discusión interesante tanto para los del grupo español como los del grupo binlingüe, he abierto este issue aquí, para que podáis comentarlo o discutirlo. 

Algún año, para poder trabajar en este tema, creamos un repositorio concreto que contenía una especificación común. Por ejemplo, este fue el [repositorio del cuso 2019-20](https://github.com/Arquisoft/viadeSpec). 

He creado otro repositorio denominado [lomapSpec](https://github.com/Arquisoft/lomapSpec). El repositorio está actualmente vacío pero por supuesto, todos podéis contribuir.

**Comment by gonzalo-rr** [comment]
Buenas tardes,

en primer lugar, me gustaría preguntar de qué API estamos hablando. Si se está hablando de la API que se utiliza para interactuar con los PODs de los usuarios, no creo que sea necesario especificar qué devuelve la API. Creo que lo fundamental es definir cómo se almacenarán los datos en los POD de SOLID, para que dichos datos puedan ser compartidos entre las diferentes aplicaciones de LoMap.

En segundo lugar, según el [guion de la práctica](https://arquisoft.github.io/course2223/labEnunciadoPractica.html) algunos de los requisitos de alto nivel son:

- Los usuarios pueden añadir lugares en categorías diferentes: tiendas, bares, restaurantes, paisajes, monumentos, etc.
- Los usuarios pueden asociar puntuaciones, comentarios, fotos, etc. sobre los lugares añadidos.

Por lo que me gustaría proponer almacenar los 'lugares' en los PODs de SOLID, con al menos la siguiente información asociada a ellos: categoría, puntuación, comentarios y fotos.

En tercer lugar, me gustaría preguntar qué formato creéis que se debería utilizar para almacenar información de los lugares. Por lo que yo tengo entendido, dentro de los PODs de SOLID se puede almacenar información en formato [RDF](https://docs.inrupt.com/developer-tools/javascript/client-libraries/structured-data/), que es el formato que utiliza SOLID o mediante archivos (.txt, .json, .jpg, etc). No sé mucho acerca del formato RDF, por lo que es muy posible que tenga una idea equivocada de lo que es así que por favor, corregidme si me he equivocado en alguna parte.

Un saludo.

**Comment by DavidGonzalezFernandez** [comment]
> en primer lugar, me gustaría preguntar de qué API estamos hablando. Si se está hablando de la API que se utiliza para interactuar con los PODs de los usuarios, no creo que sea necesario especificar qué devuelve la API. Creo que lo fundamental es definir cómo se almacenarán los datos en los POD de SOLID, para que dichos datos puedan ser compartidos entre las diferentes aplicaciones de LoMap.

Coincido con @gonzalo-rr, la idea es encontrar una especificación común que permita la interoperabilidad entre los datos almacenados por las aplicaciones que vamos a desarrollar. Definir cabeceras y tipos de las llamadas a una API para interactuar con los PODs entiendo que ya es tarea de cada grupo.

> Por lo que me gustaría proponer almacenar los 'lugares' en los PODs de SOLID, con al menos la siguiente información asociada a ellos: categoría, puntuación, comentarios y fotos.

Respecto a la información que propones almacenar hay que tomar algunas decisiones:
- ¿Un "lugar" puede pertenecer a más de 1 categoría?
- ¿Las categorías se podrán definir libremente por los usuarios, o estos únicamente podrán escoger entre las categorías predefinidas en el enunciado de la práctica?
- Si se permite a los usuarios definir libremente las categorías ¿se implementaría algún mecanismo para detectar categorías duplicadas (mismo nombre en mayúsculas o en minúsculas)?
- ¿La puntuación sería un valor numérico? Si es así, ¿dentro de qué rangos?
- ¿Los comentarios tendrán una longitud máxima permitida?

Puesto que los [requisitos de alto nivel](https://arquisoft.github.io/course2223/labEnunciadoPractica.html#requirements) de la práctica dan pie a añadir más información, a la hora de interpretar la información almacenada en los PODs tenemos que suponer que los lugares pueden contener más información que la descrita anteriormente.

Además, hay que diseñar una especificación flexible que permita añadir la información requerida para implementar las [características opcionales](https://arquisoft.github.io/course2223/labEnunciadoPractica.html#OPTIONAL) (rutas, roles, mapas entre grupos de usuarios, etc.), para en un futuro no tener que diseñar una nueva especificación incompatible con la anterior.

Finalmente, para garantizar la compatibilidad de los datos, creo que habría que indicar qué especificación (un número de versión, por ejemplo) se está utilizando. De esta forma, si se modificase la especificación (idealmente no haría falta), se podría comprobar si los datos cumplen con la última versión soportada por nuestra aplicación o no.

**Comment by gonzalo-rr** [comment]
En cuanto a los puntos que comenta @DavidGonzalezFernandez : 

No encuentro un ejemplo de un 'lugar' que pueda pertenecer a más de una categoría por lo que propondría que fuese solo una, pero si alguien pone algún ejemplo de 'lugar' que pueda pertenecer a más de una categoría se debería guardar un conjunto de categorías.

No tengo una opinión clara de si los usuarios deberían poder añadir nuevas categorías. Si fuese así aparecerían problemas como el que comenta @DavidGonzalezFernandez de categorías duplicadas, sin embargo, puede ser difícil definir todas las categorías posibles. Yo preferiría definirlas como parte de la especificación y no permitir a usuarios crear nuevas categorías.

La puntuación es lógico que sea una puntuación numérica. Además, por familiaridad y similitud a otras aplicaciones similares creo que debería ser una puntuación de 0 a 5 (similar a las estrellas en aplicaciones de mapas o de reseñas en restaurantes etc).

Creo que es razonable una longitud máxima en los comentarios, aunque no creo que sea muy relevante el número de caracteres, lo importante es que haya un límite establecido.

En cuanto a las características opcionales, imagino que pueden existir información opcional dentro de un 'lugar'. No sé si esto sería suficiente para permitir todas las características opcionales por lo que no puedo aportar mucho más.

Por último, me parece una idea interesante un número de versión.
