### ISSUE TITLE
Doubt about the deploy

### ISSUE THREAD

**Issue by gitblanc** [Arquisoft/faq#44]
Is necessary to have a deployment in AWS or in Azure? In my case, I made a deploy using Netlify in an Ubuntu 20.04 LTS and works perfectly with continuous integration

**Comment by labra** [comment]
No, it is not necessary to deploy in Azure or AWS, each team can choose to deploy the app using the provider that they want or even deploy it using more than one provider, in which case, they can even create a nice comparison between different deployment alternatives.
