### ISSUE TITLE
Problema con las prueba de carga de Gatling

### ISSUE THREAD

**Issue by Pablo-ArgF** [Arquisoft/faq#46]
Estoy intentando hacer las pruebas de carga para [nuestra aplicación](https://github.com/Arquisoft/lomap_en2a) y me encuentro con el problema que al realizarlo como indica en el documento de laboratorio se bloquean algunas de las peticiones que Lomap hace a servicios como GoogleMaps o SolidCommunity.
Estoy utilizando el proxy al igual que se indicó en las prácticas de laboratorio generando unos certificados en una carpeta cualquiera (como se indicó tambien en los laboratorios).
A continuación unas capturas que muestran los errores por consola al intentar cargar e iniciar sesion con la aplicación.
![image](https://user-images.githubusercontent.com/98907723/234962351-b7e16105-f5ac-4414-8bc5-458e97a9c0e2.png)
He intentado buscar solución en internet y otra alternativa que encontré era utilizando un archivo .har que descargo del panel de 'Networking' dentro de las developer tools del navegador. Pero esta alternativa tampoco ha funcionado al devolver un error que al parecer es un error reportado pero no arreglado aún como se puede ver en un issue del repositorio gatling https://github.com/gatling/gatling/issues/4407 referenciado también en este [post ](https://stackoverflow.com/questions/75992213/export-to-har-file-unsuccessfull-error-while-processing-har-file-c-f-j-d-jsonm) de StackOverflow. He probado a intentar descargar una version anterior de Gatling sin exito.
![image](https://user-images.githubusercontent.com/98907723/234963102-81fcf7e5-a2ad-49c7-b1c7-3da3a103488f.png)
Me pregunto si alguien más está teniendo problemas similares con sus aplicaciones y si así es, si han encontrado alguna solución al problema.

**Comment by labra** [comment]
Se me ocurren algunas alternativas:

- La grabación en el caso de gatling es simplemente para generar el código que luego permite realizar las pruebas de carga, ese código generado puede ser Java, Scala o Kotlin. Si tienes el código que dicha grabación genera o lo editas tú mismo, puedes saltarte el paso de la grabación para poder ejecutar las pruebas de carga de forma más manual. Si durante dicha ejecución hubiese un error, podrías incluso tratar de depurarlo.
- La otra posibilidad sería seguir insistiendo con la grabación pero intentar ir poco a poco...desde una aplicación más sencilla, tipo lomap_0 para ir añadiendo poco a poco características como el acceso a Solid sin mapas, o el acceso a mapas sin solid y ver cuál de las 2 es la que falla, o si son las dos. Pero vamos, la mejor estrategia para atacar estos problemas es tratar de dividirlos en problemas más pequeños para intentar localizar el punto concreto en el que falla y aislar la causa de ese fallo.
- Otra posibilidad sería cambiar de herramienta para hacer las pruebas de carga con otra herramienta...en la última sesión de clases de laboratorio, os enseñé la herramienta ab (https://httpd.apache.org/docs/2.4/programs/ab.html) que podría utilizarse para hacer unas pruebas de carga más rudimentarias. En realidad hay mucha otras herramientas para realizar pruebas de carga. Buscando en Google encontré ésto: https://pflb.us/blog/best-load-testing-tools/
