### ISSUE TITLE
Problema con el éscaner de Bugs de Sonar

### ISSUE THREAD

**Issue by Omitg24** [Arquisoft/faq#48]
Buenas tardes, revisando los últimos detalles del proyecto, de repente han comenzado a salir una gran cantidad de bugs que nunca antes habían salido, teniendo en cuenta que gran parte de los bugs que el quality gate está detectando, son de código que no se ha tocado en mínimo 2 semanas o más, pero que ahora lo detecta como tal.

Tras ponerme en contacto con más estudiantes de la asignatura, hemos visto que no solo es en un grupo, sino que está comenzando a pasar en varios equipos que no han hecho nada más que seguir trabajando como hasta ahora.

¿A que se puede deber esto? ¿Y se podría solucionar de una forma rápida? Ya que, al menos en nuestro grupo estamos tratando de arreglarlos, pero sin éxito, debido a que nunca antes habíamos visto este problema.

Muchas gracias,
Omar Teixeira

**Comment by marcosValin15** [comment]
Buenas tardes, nuestro grupo también se ha visto afectado por lo que ha comentado Omar.

**Comment by uo282936** [comment]
Buenas, mi grupo también ha experimentado este inconveniente. Llevábamos con 0 Bugs desde el principio y ahora de repente aparecen una barbaridad de ellos. Y entonces esto impide pasar el quality gate.

**Comment by labra** [comment]
Gracias por informarnos...¿podríais intentar explicar con algo más de detalle basado en un bug concreto la razón por la que está ahora avisando de que es un bug y antes no lo hacía?

**Comment by Omitg24** [comment]
En el caso de mi grupo empezó a darnos este error:

_Promise-returning function provided to attribute where a void return was expected_

Lo hemos conseguido arreglar, pero no extrañó que esto sucediera de repente

**Comment by labra** [comment]
Es que con la información que estáis dando no podemos ayudar mucho...porque entiendo que sí que estáis de acuerdo con que es correcto que esté reportando el error y lo único que ha pasado es que antes no lo hacía.

Los motivos por los que antes no lo hacía pueden ser varios...entre los que podría ser que hubiese un cambio en la configuración de Sonar, o que antes no estuviese bien configurado y ahora lo hayáis configurado mejor...en cualquier caso, si está funcionando adecuadamente, lo único razonable que podéis hacer es tratar de corregir esos bugs.

**Comment by UO271588** [comment]
A nosotros ahora mismo nos pone que no existen bugs pero tampoco existe cobertura alguna.

**Comment by labra** [comment]
Eso seguramente es otro problema diferente, que suele pasar cuando vuestro sistema de integración continua no está enviando los informes de las pruebas a Sonar. Huele a que tenéis algo mal configurado.

**Comment by UO271588** [comment]
Esta configurado correctamente porque ayer mismo teníamos una cobertura del 20 % se puede ver perfectamente en sonar y en la rama master

**Comment by labra** [comment]
No estoy 100% seguro, pero al entrar en vuestro repositorio me parece que sale el warning que había comentado en el issue: #42

Echadle un ojo a ver si vuestro problema es que no se están actualizando los informes de cobertura tal y como se indicaba en issue (en ese issue también incluí la solución).
