### ISSUE TITLE
Falllo de Diff y Deltas en Codacy

### ISSUE THREAD

**Issue by luisfesu** [Arquisoft/faq#6]
Al intentar crear una PR desde una branch, Codacy ha dado el siguiente fallo de Codacy:

![errores codacy](https://user-images.githubusercontent.com/58345609/111078362-4b4b1d80-84f5-11eb-8c4e-c30c4650e7fb.jpg)

Según la documentación de Codacy este problema puede deberse a un error por __line-endings__ incompatibles, pero nunca antes había aparecido.

**Comment by pglez82** [comment]
Hola Luis,

Si que es un error raro. Al parecer codacy está teniendo problemas al realizar un diff para saber que cambios nuevos se van a introducir con esta pull request (de cara a analizarlos). Como dices esto aparece en la documentación de codacy (https://docs.codacy.com/faq/troubleshooting/error-line-endings/). Tenéis que investigar que commit es el que ha causado eso (el que ha introducido estos caracteres), para poder corregirlo. Probablemente es alguien del equipo que tiene configurado el entorno de desarrollo para meter esos caracteres al final de las líneas. 

Una idea que se me ocurre es ejecutar `git diff` a mano en esta rama (en teoría debería de fallar para algún archivo) y ver si nos da alguna pista más de cara a encontrar el error.
