### ISSUE TITLE
Fallo gyp-node al hacer npm i 

### ISSUE THREAD

**Issue by cova-vega** [Arquisoft/faq#7]
Me sale este fallo al hacer npm i.  Seguí los pasos que me marcó la profesora de laboratorio para ver si lo podiamos solucionar y nada. Tambien me da fallo al hacer npm start me dice que no tengo dotenv-expand 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/56292685/111609261-68743a80-87da-11eb-89e9-9cba0a30f047.png)

**Comment by cidinene** [comment]
En el error te da una referencia a los pasos a seguir para que funcione en Windows https://github.com/nodejs/node-gyp#on-windows.. yo creo que la versión de Visual Studio que instalamos ayer no es la misma.. yo volvería a intentar seguir los pasos fijándome en las versiones referidas

**Comment by cova-vega** [comment]
Lo he vuelto a intentar instalando el visual studio community 2017 y los pasos que me especifican ahí y me pasa lo mismo

**Comment by pglez82** [comment]
Buenos días. ¿Hay alguna razón por la que instalas esa versión de visual studio? Yo me instalaría la última versión de visual studio code descargada de [aquí](https://code.visualstudio.com/download). La última versión es la 1.54.3

**Comment by cova-vega** [comment]
Me lo acaba solucionar @cidinene . Era por un conflicto en el paquete json con la versión de react y react-dom en mi grupo que era la 17 y me daba error en el date-fns . Entonces borramos node modules, cambiamos a la versión 16 de react en y de react-dom el json. Reinstalamos  y ejecutamos y funcionó
